language: shell
services:
- docker

stages:
  - name: install
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
  - name: script
    # require the branch name to be master (note for PRs this is the base branch name)
    if: tag = true

env:
#  matrix:
  global:
#  - DOCKER_TAG=$TRAVIS_BUILD_ID
  - DOCKER_TAG=${TRAVIS_COMMIT:0:7}
  - DEV_REPO=blademainer/hexo-editor:$DOCKER_TAG
  - RELEASE_REPO=blademainer/hexo-editor:$TRAVIS_TAG
before_install:
- env
- docker login -u$DOCKER_USER -p$DOCKER_PASS

install:
- docker build . -t $DEV_REPO && docker push $DEV_REPO
script:
- if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
- docker pull $DEV_REPO
- docker tag $DEV_REPO $RELEASE_REPO && docker push $RELEASE_REPO
